### ISSUE TITLE
trigger_gravity & consorts makes the player tremble

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2031]
As "reported" [here](https://github.com/Unvanquished/unvanquished-mapeditor-support/blob/1226cf262f6476e4d1ddeb2ffd867f3d3de8a5d6/src/entities/entities.yaml#L1118-L1123):

```
- name: env_afx_gravity
# bug: local negative (<0) gravity fights with level gravity causing player to tremble
  extend: [chain_autonom]
  color: 7f7f7f
  props:
    amount: The gravity within this entity.
```

Negative gravity seems to make player shake. A way to reproduce this is by connecting to pushpad-test map:

* pusher marked with "1" does not shakes
* pusher marked with "2" does shakes

Another way is to play on `zittrig-arena` from cu-kai.

Another thing is, this seems to not happen when following or watching at a player using those, so it might be a client prediction bug.
There is currently no way to know if this is linked to pusher+anti-grav or only the gravity settings.
