### ISSUE TITLE
 Built-in shaders failed: Couldn't compile fragment shader: vertexLighting_DBS_entity

### ISSUE THREAD

**Issue by wtfbbqhax** [Unvanquished/Unvanquished#967]
Built latest master (`commit f7ed9d9bebd6f4b264571f99dafa3d31cf833240`), getting that _ERR_ . 

Pak's were retrieved by `./download_pk3.sh` moments prior
# Log Snippet

``` yaml
Warn: SSAO not used because GL_ARB_texture_gather is not available.
Warn: Source for shader program vertexLighting_DBS_entity:
#version 120
#ifndef USE_SHADER_LIGHTS
#define USE_SHADER_LIGHTS 1
#endif
float smoothstep(float edge0, float edge1, float x) { float t = clamp((x - edge0) / (edge1 - edge0), 0.0, 1.0); return t * t * (3.0 - 2.0 * t); }
#ifndef TEXTURE_RG
#define TEXTURE_RG 1
#endif
#ifndef TEXTURE_INTEGER
#define TEXTURE_INTEGER 1
#endif
#ifndef r_AmbientScale
#define r_AmbientScale 1.000000
#endif
#ifndef r_SpecularScale
#define r_SpecularScale 1.000000
#endif
#ifndef r_NormalScale
#define r_NormalScale 1.000000
#endif
#ifndef r_zNear
#define r_zNear 3.000000
#endif
#ifndef M_PI
#define M_PI 3.141593
#endif
#ifndef MAX_SHADOWMAPS
#define MAX_SHADOWMAPS 5
#endif
#ifndef MAX_REF_LIGHTS
#define MAX_REF_LIGHTS 1024
#endif
#ifndef TILE_SIZE
#define TILE_SIZE 16
#endif
#ifndef r_FBufScale
#define r_FBufScale vec2(0.000781, 0.001250)
#endif
#ifndef r_tileStep
#define r_tileStep vec2(0.012500, 0.020000)
#endif
#ifndef r_precomputedLighting
#define r_precomputedLighting 1
#endif
#ifndef r_VertexSkinning
#define r_VertexSkinning 1
#endif
#ifndef MAX_GLSL_BONES
#define MAX_GLSL_BONES 233
#endif
#ifndef r_WrapAroundLighting
#define r_WrapArou
        // compute view direction in world space
        vec3 V = normalize(u_ViewOrigin - var_Position);

        vec2 texDiffuse = var_TexDiffuse.st;

#if defined(USE_NORMAL_MAPPING)
        mat3 tangentToWorldMatrix = mat3(var_Tangent.xyz, var_Binormal.xyz, var_Normal.xyz);

        vec2 texNormal = var_TexNormalSpecular.xy;
        vec2 texSpecular = var_TexNormalSpecular.zw;

#if defined(USE_PARALLAX_MAPPING)

        // ray intersect in view direction

        // compute view direction in tangent space
        vec3 Vts = (u_ViewOrigin - var_Position.xyz) * tangentToWorldMatrix;
        Vts = normalize(Vts);

        // size and start position of search in texture space
        vec2 S = Vts.xy * -u_DepthScale / Vts.z;

#if 0
        vec2 texOffset = vec2(0.0);
        for(int i = 0; i < 4; i++) {
                vec4 Normal = textur
Warn: Compile log:
ERROR: 0:134: '' : syntax error: preprocessor command must not be preceded by any other statement in that line
ERROR: 0:134: 'premature EOF' : syntax error syntax error

Warn: Built-in shaders failed: Couldn't compile fragment shader: vertexLighting_DBS_entity
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.50.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.49.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.48.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.47.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.46.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.45.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.44.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.43.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.42.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.41.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.40.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.39.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.38.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.37.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.36.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.35.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.34.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.33.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.32.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.31.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.30.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.29.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.28.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.27.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.26.0.pk3'...
[FS] Loading pak '/Users/viroemer/Library/Application Support/Unvanquished/pkg/unvanquished_0.25.0.pk3'...
```
